name: Build Push github pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python3 -m pip install nox

      - run: nox -s docs

      - name: Push to gh-pages branch for publication from main
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3

        - name: Install gems
          run: |
            gem install html-proofer
            gem install typhoeus

        - name: Cache HTMLProofer
          id: cache-htmlproofer
          uses: actions/cache@v4
          with:
            path: tmp/.htmlproofer
            key: ${{ runner.os }}-htmlproofer

        - name: Run htmlproofer
          run: |
            ruby scripts/htmlproofer.rb
            ls
